### PR TITLE
plot lumi ccdb

### PR DESCRIPTION
**Pull request by jrstevenjlab**
Use target density in CCDB to compute luminosity with uncertainty and store as histogram of luminosity vs beam energy.  Users may specify the appropriate target length on the command line.

### CODE REVIEW

**Comment by jrstevenjlab** [comment]
bump

**Comment by aaust** [comment]
When I run it, I get the following warning:
`TH1F::Sumw2:0: RuntimeWarning: Sum of squares of weights structure already created`
The histogram itself looks good.

**Comment by jrstevenjlab** [comment]
With the latest commits I fixed the underlying issue with the apparent "fluctuations" in the energy-dependent normalization, reported at the beamline and collaboration meetings https://halldweb.jlab.org/DocDB/0047/004732/001/flux_syst_10.23.20.pdf (slide 5-6).  

The basic problem was that the PS acceptance was being divided out at the histogram level, rather than the individual tagger counter level.  This of course would give different results if you use 5 or 100 MeV wide energy bins, since the PS acceptance would be evaluated at the center of the histogram bins.

The PS acceptance divided out from the counter-by-counter flux from CCDB, resulting in an the same tagged flux distribution for different initial binning choices and rebidding.  The resulting flux normalized yields no longer have the scatter at low energy we've observed previously.

This is ready for someone to review and merge if it's acceptable.

**Comment by rjones30** [comment]
This sounds good. -rtj

**Pull request merged**
